### ISSUE TITLE
[Help] Keycode Modiefiers

### ISSUE THREAD

**Issue by ScarVite** [KingPendragoon/FFXIVJobPrioGaolAutoMarker#1]
as i use my f1-f8 keys for targeting, i wanted to bind the macros to alt+f1-f9

if i understood it correctly, the keycode for alt+f1 should be `131184`

but it's not executing my macro which is bound to alt+f1 instead it just activates the f1 action instead.

do you know why it might not work, is there too much delay between the keypresses or are they just too simultaneous for ffxiv

Hoping for any help

**Comment by KingPendragoon** [comment]
To my understanding the issue lies within how triggernometry was programmed.  For some reason when trig tries to send modifier keys ffxiv does not receive the modifier and only the key.  Unfortunately there is not really a work around for this.
