### ISSUE TITLE
Triggers fail on mark actions

### ISSUE THREAD

**Issue by nasahapps** [KingPendragoon/FFXIVJobPrioGaolAutoMarker#2]
If you do a fresh install of auto markers, it always fails on the `MarkerPriority` action with the following error using the test macro (or if you're actually in UWU):

```
Exception: startIndex cannot be larger than legnth of string. Parameter name: startIndex
```

**Comment by Fijvect** [comment]
So how did you fix this? I'm experiencing this issue right now unfortunately (while in UWU) :(
